### PR TITLE
[Docs] documenting some undocumented Get methods

### PR DESCRIPTION
**Pull request by Nipodemos**
### Warning: this PR needs that #321 be merged BEFORE, this current PR is a followup

hey @jonataslaw, you forgot to document these methods 😅

### CODE REVIEW

**Comment by Nipodemos** [comment]
dammit, now it got duplicated commits... i have no idea how to remove that

**Comment by Nipodemos** [comment]
fixed commits!
now you can review and merge @jonataslaw

**Comment by Nipodemos** [comment]
@jonataslaw why i can do `Get.width/height` but the other context-dependent methods a need to use like `Get.context.orientation`?

the second one makes more sense, the strange is having both at same time

**Comment by jonataslaw** [comment]
In fact, other methods do not need "Get", they can be accessed directly from the context.
Get.height and Get.width gives the screen size. It is immutable. This can be useful if you want to make an immutable pattern of layout.
context.width in turn, provides the "current" size of the screen width. If you open a keyboard on your phone, resize the browser screen, it will change and give you the updated value.

**Comment by Nipodemos** [comment]
whaaaat
this gotta be documented. I thought that widthTransformer that did the task of adapt with screen size changes.... lol
wait i'll put this on docs

**Comment by Nipodemos** [comment]
now I think it is ready for merge

**Comment by jonataslaw** [comment]
I got scared now with this Coverage message kkkk
I don't remember setting this up on the account, I must have done it during the night, dying of sleep kkk

**Comment by Nipodemos** [comment]
this code cov was sooo random kkkkkkk
i thuoght you were doing the configuration in the middle of PR

**Pull request merged**
