### PR TITLE
Create an Event Rx holder to call listeners when the same value is passed

### PR DESCRIPTION
**Pull request by RafaRuiz**
This idea comes half-way from the [SingleLiveEvent of Android and Kotlin](https://medium.com/@abhiappmobiledeveloper/android-singleliveevent-of-livedata-for-ui-event-35d0c58512da), although this one doesn't keep the value afterwards (maybe if it's interesting, I can make it work in both ways!); this new `RxEvent<T>` will notify the listeners through `RxEvent<T>.trigger(T)`.

Imagine you're creating an `Obx(builder)` where the builder animates a Widget for `2` seconds, and you want to animate that according to a logic variable: `RxEvent<int> secondsAnimation = RxEvent<int>(2)`. After an user iteration, you might want to animate that again to 2 seconds as well: `secondsAnimation.trigger(2)` will trigger the listeners again (`.call(2)` or `.value = 2` won't!). 

I'm up to hear some feedback, or event remove entirely the `RxEvent<T>` class and add the `.trigger(T)` method into `Rx<T>`.

### CODE REVIEW

**Comment by jonataslaw** [comment]
Interesting feature, but I was thinking, trigger could be part of the core instead of having its own Rx for that. It could be in _RxImpl to allow it to be used in existing Rx variables

**Comment by RafaRuiz** [comment]
Thanks for the answer. I'll update that!

**Comment by RafaRuiz** [comment]
All changed now @jonataslaw

**Comment by jonataslaw** [comment]
Thanks for your contribution, LGTM!

**Pull request merged**
