### PR TITLE
add routerConfig

### PR DESCRIPTION
**Pull request by Riadloc**
issue #2610 #2545 

flutter official commit [here](https://github.com/flutter/flutter/pull/102786)

### CODE REVIEW

**Review by Ajjig — APPROVED** [review]

**Comment by mitesh77** [comment]
we can use with go_route package after this add routerConfig  @Riadloc @Ajjig ?

**Comment by duc1205** [comment]
@Riadloc what you added just to make it look like go_router but not usable?

**Comment by Riadloc** [comment]
@duc1205 because this pr not merged yet. 😂

**Comment by duc1205** [comment]
@Riadloc i see you are just giving getx's getpage the same as go_router. is that true?

**Comment by duc1205** [comment]
@jasonlaw

**Comment by duc1205** [comment]
@jonataslaw

**Comment by jonataslaw** [comment]
Thanks for your contribution
LGTM

**Comment by duc1205** [comment]
when release 5.0 @jonataslaw ?

**Comment by duc1205** [comment]
@jonataslaw when use go_router in getx master, i see Getx required add **getPages** 
image

**Comment by mbfakourii** [comment]
> @jonataslaw when use go_router in getx master, i see Getx required add **getPages** image

and get ```You need add pages or home``` !

**Pull request merged**
