### PR TITLE
Fix to rx.trigger so that it checks for previous send to stream by set value

### PR DESCRIPTION
**Pull request by gslender**
This fixes issue #1933 

- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or @jonataslaw said the PR is test-exempt.
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by jonataslaw** [comment]
Hi, thanks for your contribution,
I was able to reproduce this problem with your code.
Could you please duplicate this test and add different numbers?
I think this will cover us with the hypothesis of equal values and different values, which was just what we needed to identify this bug.

Sorry for the delay, we're busy with the new version and selecting only PRs that maintain backward compatibility to merge, which seems to be the case for this one.

**Comment by gslender** [comment]
I'm unsure in what you're saying you've found, as the test changes I submitted in my PR have exactly different numbers being tested and the results are correct.

e.g....

```
    // we call 3
    reactiveInteger.trigger(3);
    // then repeat twice
    reactiveInteger.trigger(3);
    reactiveInteger.trigger(1);

    await Future.delayed(Duration(milliseconds: 100));
    expect(3, timesCalled);

```

**Comment by gslender** [comment]
Perhaps the comments in the test are not 100% accurate, but I changed as little as possible assuming you'd want to verify and own the changes to confirm either a) that indeed my fix is correct and b) that the tests are more broadly correct

**Comment by jonataslaw** [comment]
Nvm I do it

**Comment by zenas** [comment]
> Nvm 我做到了

According to the difference between trigger and call, maybe we just need to consider _value == v 。

like:
`
void trigger(T v){
  if(_value == v){
    var firstRebuild = this.firstRebuild;
    if(fistRebuild){
    subject.add(v)
  }
  }else{
    value = v
  }
}
`

**Pull request merged**
