### PR TITLE
Adding route guards and improving navigation

### PR DESCRIPTION
**Pull request by ahmednfwela**
## Pre-launch Checklist

- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or @jonataslaw said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by ahmednfwela** [comment]
cc @jonataslaw @Azzeccagarbugli @jasonlaw 
fixes: https://github.com/jonataslaw/getx/issues/1602
fixes: https://github.com/jonataslaw/getx/issues/1620
fixes: https://github.com/jonataslaw/getx/issues/1537

**Comment by jasonlaw** [comment]
@ahmednfwela Thank you very much!

**Comment by jonataslaw** [comment]
Wow, thanks! LGTM

**Comment by Azzeccagarbugli** [comment]
Thank you, the PR is perfectly working!

**Comment by ahmednfwela** [comment]
@Azzeccagarbugli Link me the repo and I will try to help 👍

**Comment by Azzeccagarbugli** [comment]
> @Azzeccagarbugli Link me the repo and I will try to help 👍

https://github.com/Azzeccagarbugli/getx_navigation

**Comment by jonataslaw** [comment]
@ahmednfwela 

1- For some reason, history is being cleared when the initial route is being pushed, and a black screen is displayed, if for example we use this code snippet:


```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp.router(
      getPages: [
        GetPage(
            participatesInRootNavigator: true,
            name: '/first',
            page: () => First()),
        GetPage(
          name: '/second',
          page: () => Second(),
        ),
        GetPage(
          name: '/third',
          page: () => Third(),
        ),
      ],
      debugShowCheckedModeBanner: false,
      routeInformationParser: GetInformationParser(initialRoute: '/first'),
      routerDelegate: GetDelegate(),
    );
  }
}

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('page one'),
        leading: IconButton(
          icon: Icon(Icons.more),
          onPressed: () {
            Get.changeTheme(
                context.isDarkMode ? ThemeData.light() : ThemeData.dark());
          },
        ),
      ),
      body: Center(
        child: Container(
          height: 300,
          width: 300,
          child: ElevatedButton(
            onPressed: () {},
            child: Text('next screen'),
          ),
        ),
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('page two ${Get.parameters["id"]}'),
      ),
      body: Center(
        child: Container(
          height: 300,
          width: 300,
          child: ElevatedButton(
            onPressed: () {},
            child: Text('next screen'),
          ),
        ),
      ),
    );
  }
}

class Third extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      appBar: AppBar(
        title: Text('page three'),
      ),
      body: Center(
        child: Container(
          height: 300,
          width: 300,
          child: ElevatedButton(
            onPressed: () {},
            child: Text('go to first screen'),
          ),
        ),
      ),
    );
  }
}
```

I don't know if this was caused by the last Flutter update, or some code of ours, but it prevents users from using GetDelegate, using Navigator 2 without RouterOutlet. Since you basically recreated this, maybe you know what's causing it.

2: You've been doing a great job, do you have something like BuyMeACoffee or something similar? I think myself and other users would like to contribute you work.

3- I think I received a message from a user on some social network, but I'm not sure if it's you, if it was you, please confirm me so I can answer you.

**Comment by ahmednfwela** [comment]
@jonataslaw 
1- If you change the snippet to this, it works: 
```dart
void main() {
  final infoParser = GetInformationParser(initialRoute: '/first');
  final delegate = GetDelegate();
  runApp(
    MyApp(
      delegate: delegate,
      informationParser: infoParser,
    ),
  );
}

class MyApp extends StatelessWidget {
  MyApp({
    Key? key,
    required this.informationParser,
    required this.delegate,
  }) : super(key: key);
  final GetInformationParser informationParser;
  final GetDelegate delegate;
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp.router(
      getPages: [
        GetPage(
            participatesInRootNavigator: true,
            name: '/first',
            page: () => First()),
        GetPage(
          name: '/second',
          page: () => Second(),
        ),
        GetPage(
          name: '/third',
          page: () => Third(),
        ),
      ],
      debugShowCheckedModeBanner: false,
      routeInformationParser: informationParser,
      routerDelegate: delegate,
    );
  }
}
```

I am not sure why, but for some reason the root stateless widget gets rebuilt twice, so we need to make sure the construction of the `GetDelegate` and `GetInformationParser` happens only once.

And since we have our own dependency management, we can even go the extra mile to do this: 
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp.router(
      getPages: [
        GetPage(
            participatesInRootNavigator: true,
            name: '/first',
            page: () => First()),
        GetPage(
          name: '/second',
          page: () => Second(),
        ),
        GetPage(
          name: '/third',
          page: () => Third(),
        ),
      ],
      debugShowCheckedModeBanner: false,
      routeInformationParser:
          Get.put(GetInformationParser(initialRoute: '/first')),
      routerDelegate: Get.put(GetDelegate()),
    );
  }
}
```
Which allows us to do `Get.find<GetDelegate>()` if we feel like it 💯 

2- I am very grateful to you and everyone, I just created this page https://www.buymeacoffee.com/bdayadev and I appreciate any support😄 

3- yes that was my discord account `Ahmed Fwela#3051`

**Comment by Azzeccagarbugli** [comment]
Really, thanks a lot @ahmednfwela for your work! I really would like to buy you even more than one coffee 🎉

I hope you have also good news about this 🥲

> > @Azzeccagarbugli Link me the repo and I will try to help 👍
> 
> https://github.com/Azzeccagarbugli/getx_navigation

**Comment by jonataslaw** [comment]
Thanks for the reply, and yes, parseRouteInformation will rebuild everything under `runApp`, to make the initial route, the exact route described, it's a default behavior of Flutter 2.2, and as a new instance of the delegate is recreated, it has a new List instance and an empty history. I hadn't thought of that, Great catch, I think we can insert these two classes as permanents inside GetNavigationExt, I'm actually thinking about recreating the GetNavigationExt methods inside Get.delegate, and when calling Get.toNamed, just create an alias for it Get.getDelegate().toNamed.
I want to rely less on NavigatorKey, because it invokes a widget, and that would be a progression in testing, as we could test the navigation in a unitary way.
This week I'm going to send this version to the pub, so I'm just making sure to change everything now so we don't have breaks after release

**Comment by ahmednfwela** [comment]
@jonataslaw we could have 2 modes for navigation, one that interacts with the navigator key, and one with the get delegate, because we still need the old navigation for dialogs/snackbars/etc...

also @Azzeccagarbugli lets move the discussion here https://github.com/Azzeccagarbugli/getx_navigation/issues/1

**Comment by steven-spiel** [comment]
This is a huge improvement! Thank you! I'm noticing that fullscreenDialog doesn't really go fullscreen if it is nested, it only takes the full area of the container. Is that the intended behavior?

**Comment by steven-spiel** [comment]
Actually, looks like i didn't have the latest. 4ddc3481ce6237b313e2097840c1fd00f57aa85e has `participatesInRootNavigator` which I think is what I need.

**Comment by steven-spiel** [comment]
*sad trombone* 

Maybe I'm not understanding it, but here is an example of what I'm trying to do:

Video:

https://user-images.githubusercontent.com/77690617/125353925-2ba3f480-e331-11eb-8c3a-1257c0b3f665.mp4

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/get_navigation/src/nav2/get_router_delegate.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(GetMaterialApp.router(
    title: "Application",
    routeInformationParser: GetInformationParser(),
    routerDelegate: GetDelegate(),
    getPages: <GetPage<dynamic>>[
      GetPage<dynamic>(
        name: '/',
        page: () => Root(),
        participatesInRootNavigator: true,
        children: <GetPage<dynamic>>[
          GetPage<dynamic>(
            name: '/page2',
            page: () => Page2(),
            participatesInRootNavigator: true,
            children: <GetPage<dynamic>>[
              GetPage<dynamic>(
                name: '/modal',
                page: () => Modal(),
                participatesInRootNavigator: true,
                fullscreenDialog: true,
              ),
            ],
          ),
        ],
      ),
    ],
  ));
}

class Root extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          border: Border.all(
            color: Colors.blue,
            width: 15,
          ),
        ),
        child: GetRouterOutlet(
          name: '/',
          pickPages: (currentNavStack) {
            return currentNavStack.currentTreeBranch.pickAfterRoute('/');
          },
          emptyWidget: (delegate) => Scaffold(
            body: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Center(
                  child: ElevatedButton(
                    onPressed: () {
                      Get.getDelegate()!.toNamed('/page2');
                    },
                    child: Text('Go to Page 2'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: ElevatedButton(
              onPressed: () => Get.getDelegate()!.toNamed('/page2/modal'),
              child: Text('open Modal'),
            ),
          ),
        ],
      ),
    );
  }
}

class Modal extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(child: Text('Should be full screen')),
        ],
      ),
    );
  }
}
```

**Comment by steven-spiel** [comment]
195b46f8075d35a6bb15f8cbc4e888bbd5ce3e1e fixes the issue I outlined above. Using `Get.toNamed('/page2/modal')` no longer throws the error that the route can't be found. It brings up the fullscreen dialog as expected. Thank you!

**Comment by steven-spiel** [comment]
I have found another issue, though. Bindings seem to not get disposed of properly once routing is nested more than once. The controller here is not getting closed. It's a simple example where the controller simply gets the `id` from `Get.parameters` and displays it.


https://user-images.githubusercontent.com/77690617/125986281-4994fdfe-2b45-4a3d-bd92-82f251a40747.mov

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(GetMaterialApp.router(
    title: "Application",
    getPages: <GetPage<dynamic>>[
      GetPage<dynamic>(
        name: '/',
        page: () => Root(),
        participatesInRootNavigator: true,
        children: <GetPage<dynamic>>[
          GetPage<dynamic>(
            name: '/books',
            page: () => Books(),
            children: <GetPage<dynamic>>[
              GetPage<dynamic>(
                name: '/:id',
                page: () => Book(),
                binding: BindingsBuilder.put(() => BookController()),
              ),
            ],
          ),
        ],
      ),
    ],
  ));
}

class BookController extends GetxController {
  final String? id = Get.parameters['id'];

  @override
  void onClose() {
    print('Controller closed');

    super.onClose();
  }
}

class Root extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetRouterOutlet(
        name: '/',
        pickPages: (currentNavStack) {
          return currentNavStack.currentTreeBranch.pickAfterRoute('/');
        },
        emptyWidget: (delegate) => Scaffold(
          body: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Center(
                child: ElevatedButton(
                  onPressed: () {
                    Get.rootDelegate.toNamed('/books');
                  },
                  child: Text('Go to Books'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class Books extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: ElevatedButton(
              onPressed: () => Get.rootDelegate.toNamed('/books/1'),
              child: Text('open Book 1'),
            ),
          ),
          Center(
            child: ElevatedButton(
              onPressed: () => Get.rootDelegate.toNamed('/books/2'),
              child: Text('open Book 2'),
            ),
          ),
          Center(
            child: ElevatedButton(
              onPressed: () => Get.rootDelegate.toNamed('/books/3'),
              child: Text('open Book 3'),
            ),
          ),
        ],
      ),
    );
  }
}

class Book extends GetWidget<BookController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(leading: BackButton(onPressed: Get.rootDelegate.popRoute)),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(child: Text('Book ${controller.id}')),
        ],
      ),
    );
  }
}
```

________________________________

However, when I remove one layer of nesting from the routing, it works as expected:

https://user-images.githubusercontent.com/77690617/125986641-f2568c95-5b68-4397-b36d-0fbd1b0fd6bd.mov

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(GetMaterialApp.router(
    title: "Application",
    getPages: <GetPage<dynamic>>[
      GetPage<dynamic>(
        name: '/books',
        page: () => Root(),
        participatesInRootNavigator: true,
        children: <GetPage<dynamic>>[
          GetPage<dynamic>(
            name: '/:id',
            page: () => Book(),
            binding: BindingsBuilder.put(() => BookController()),
          ),
        ],
      ),
    ],
  ));
}

class BookController extends GetxController {
  final String? id = Get.parameters['id'];

  @override
  void onClose() {
    print('Controller closed');

    super.onClose();
  }
}

class Root extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetRouterOutlet(
        name: '/books',
        pickPages: (currentNavStack) {
          return currentNavStack.currentTreeBranch.pickAfterRoute('/books');
        },
        emptyWidget: (delegate) => Books(),
      ),
    );
  }
}

class Books extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: ElevatedButton(
              onPressed: () => Get.rootDelegate.toNamed('/books/1'),
              child: Text('open Book 1'),
            ),
          ),
          Center(
            child: ElevatedButton(
              onPressed: () => Get.rootDelegate.toNamed('/books/2'),
              child: Text('open Book 2'),
            ),
          ),
          Center(
            child: ElevatedButton(
              onPressed: () => Get.rootDelegate.toNamed('/books/3'),
              child: Text('open Book 3'),
            ),
          ),
        ],
      ),
    );
  }
}

class Book extends GetWidget<BookController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(leading: BackButton(onPressed: Get.rootDelegate.popRoute)),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(child: Text('Book ${controller.id}')),
        ],
      ),
    );
  }
}
```

Any idea why it's not getting destroyed?

**Comment by ahmednfwela** [comment]
@steven-spiel can you create a separate issue for this?

**Comment by ahmednfwela** [comment]
also the problem is in ` binding: BindingsBuilder.put(() => BookController()),`
change it to:
```dart
binding:  BindingsBuilder(() {
      Get.create<BookController>(() => BookController());
    });
```

**Pull request merged**
