### PR TITLE
fixed an error in readme

### PR DESCRIPTION
**Pull request by nateshmbhat**

### CODE REVIEW

**Review by iMrLopez — APPROVED** [review]
Had to look for this for about an hour, thanks for the contribution!

**Comment by eduardoflorence** [comment]
Hi @nateshmbhat, could you make the same correction in the other languages present in the documentation?

**Comment by nateshmbhat** [comment]
Sure

**Comment by nateshmbhat** [comment]
@eduardoflorence Have raised the PR here : #1370

**Pull request closed without merging**
