### PR TITLE
Refactor and removed deprecated methods

### PR DESCRIPTION
**Pull request by Aniketkhote**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

Every PR must update the corresponding documentation in the `code`, and also the readme in english with the following changes.

## Pre-launch Checklist

- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or @jonataslaw said the PR is test-exempt.
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by fisforfaheem** [comment]
Thanks, kindly release this so we can benefit, because currently cant use this latest code.

**Review by jonataslaw — APPROVED** [review]
LGTM

**Comment by jonataslaw** [comment]
Thank you for your contribution!

**Comment by aniketkhote9** [comment]
Could you please publish these changes? Developers face numerous challenges, and many deprecated methods were removed in Flutter 3.22.0. This candidate version is working well, so it is ready for publication.

**Pull request merged**
