### PR TITLE
fix: #1428

### PR DESCRIPTION
**Pull request by KevinZhang19870314**
According to your comments for #1428, I made a pr and could you please kindly review it, thanks!

### CODE REVIEW

**Comment by jasonlaw** [comment]
@KevinZhang19870314 btw, why the request copyWith has mandatory parameters for url, method and headers? what if we just want to modify the headers only?

**Comment by KevinZhang19870314** [comment]
@jasonlaw 
1. Fixed the modifyResponse;
2. Remove the mandatory copyWith parameters for url, method and headers;
3. run `flutter test` and all tests passed.

```
PS D:\KevinZhang\Study\FlutterProject\getx> flutter test
00:06 +0: D:\KevinZhang\Study\FlutterProject\getx\test\benchmarks\benckmark_test.dart: percentage test
============================================
PERCENTAGE TEST
referenceValue is 100% more than requestedValue
00:06 +3: D:\KevinZhang\Study\FlutterProject\getx\test\benchmarks\benckmark_test.dart: run benchmarks from ValueNotifier
============================================
VALUE_NOTIFIER X GETX_VALUE TEST
00:06 +11: D:\KevinZhang\Study\FlutterProject\getx\test\benchmarks\benckmark_test.dart: run benchmarks from ValueNotifier
-----------
30 listeners notified | [GETX_VALUE] time: 1223ms
30 listeners notified | [VALUE_NOTIFIER] time: 3275ms
-----------
30000 listeners notified | [GETX_VALUE] time: 36243ms
30000 listeners notified | [VALUE_NOTIFIER] time: 45715ms
-----------
ValueNotifier delay 45715 ms to made 30000 requests
GetValue delay 36243 ms to made 30000 requests
-----------
GetValue is 26% faster than Default ValueNotifier with 30000 requests
00:06 +13: D:\KevinZhang\Study\FlutterProject\getx\test\benchmarks\benckmark_test.dart: run benchmarks from Streams
============================================
DART STREAM X GET_STREAM X GET_MINI_STREAM TEST
-----------
30 listeners notified | [GET_STREAM] time: 3869ms
30 listeners notified | [MINI_STREAM] time: 1072ms
30 listeners notified | [STREAM] time: 1375ms
-----------
GetStream is 28% faster than Default Stream with 30 requests
-----------
00:07 +16: D:\KevinZhang\Study\FlutterProject\getx\test\benchmarks\benckmark_test.dart: run benchmarks from Streams
30000 listeners notified | [STREAM] time: 899372ms
00:09 +18: D:\KevinZhang\Study\FlutterProject\getx\test\benchmarks\benckmark_test.dart: run benchmarks from Streams
30000 listeners notified | [GET_STREAM] time: 8844ms
30000 listeners notified | [MINI_STREAM] time: 6142ms
60000 listeners notified | [STREAM] time: 1704999ms
60000 listeners notified | [GET_STREAM] time: 6712ms
60000 listeners notified | [MINI_STREAM] time: 4117ms
-----------
dart_stream delay 1704999 ms to made 60000 requests
getx_stream delay 6712 ms to made 60000 requests
getx_mini_stream delay 4117 ms to made 60000 requests
-----------
GetStream is 41314% faster than Default Stream with 60000 requests
00:17 +30: D:\KevinZhang\Study\FlutterProject\getx\test\navigation\middleware_test.dart: Middleware redirect smoke test
/second
00:20 +52: D:\KevinZhang\Study\FlutterProject\getx\test\navigation\parse_route_test.dart: params in url by parameters
Iniciando test
00:37 +131: All tests passed!
```

But in my local forked code, some errors for source code catched by vscode, I am not sure why it happened.
image

**Comment by jasonlaw** [comment]
@KevinZhang19870314 
Thanks for the changes.
I have one more question for request's copyWith, do you think should we merge the headers instead of totally replacing it?  I am not too sure what is the standard for copyWith normally. But for my case, I may want to append the headers, instead of replacing it.

**Comment by KevinZhang19870314** [comment]
@jasonlaw I am not sure is this needed, may be some one need repalce, some need merge. I think we can add a optional parameter like `bool appendHeader = true`, which will control merge or totally replace headers or not? What's your opinion?

**Comment by jonataslaw** [comment]
Thank you for that PR @KevinZhang19870314 .
LGTM. 

@jasonlaw, I think that request.header.addAll(appendHeader) might be enough for you, correct if I'm wrong.

**Comment by KevinZhang19870314** [comment]
@jasonlaw Updated pr, hope this will be the last one ~_~

**Comment by jasonlaw** [comment]
> Thank you for that PR @KevinZhang19870314 .
> LGTM.
> 
> @jasonlaw, I think that request.header.addAll(appendHeader) might be enough for you, correct if I'm wrong.

yes, I think that is sufficient for me. thanks!

**Comment by jasonlaw** [comment]
> @jasonlaw Updated pr, hope this will be the last one ~_~

thanks!

**Pull request merged**
