### PR TITLE
possible fix for error: No named parameter with the name 'shadowThemeOnly'.

### PR DESCRIPTION
**Pull request by worldofsites**
possible fix for issue https://github.com/jonataslaw/getx/issues/762

same changes as in commit: https://github.com/flutter/flutter/commit/9fb1c521b1f6f93a668161b2e2c7c54c0e308f81#diff-2cbc1634ed6b61d61dfa090e7bfbbb7c60b74c8abc3a28df6f79eee691fd1b73R981

### CODE REVIEW

**Comment by ductranit** [comment]
I tried this commit
```
get:
    git:
      url: git://github.com/worldofsites/getx.git
      ref: d12b4d5ea72f2128e73e826b6cb71248d95366b7
```
And got another error
```
../flutter/.pub-cache/git/getx-d12b4d5ea72f2128e73e826b6cb71248d95366b7/lib/get_navigation/src/extension_navigation.dart:237:67: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
        to: Navigator.of(context, rootNavigator: useRootNavigator)!.context);
                                                                  ^
../flutter/.pub-cache/git/getx-d12b4d5ea72f2128e73e826b6cb71248d95366b7/lib/get_navigation/src/extension_navigation.dart:430:43: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(key.currentContext, shadowThemeOnly: true),
                                          ^^^^^^^^^^^^^^^
../../Soft/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^

Command PhaseScriptExecution failed with a nonzero exit code
```
Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-7.0.pre.75, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)
```

**Comment by worldofsites** [comment]
@ductranit please try now

**Comment by ductranit** [comment]
@worldofsites great! it works well.

**Comment by jonataslaw** [comment]
I will need to create another branch for this, and probably upload a beta version to the pub. However the master changes easily, I am waiting for the update to be consolidated in the dev to do something like that. Thanks for the PR

**Review by feehlemmy — APPROVED** [review]

**Comment by cyberpwnn** [comment]
This is happening on flutter beta now

**Pull request closed without merging**
