### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by gokul1630**

### CODE REVIEW

**Comment by jonataslaw** [comment]
Hi, thanks for your contribution!
Does the file in Spanish, Portuguese and Polish also have the same typo?

**Comment by gokul1630** [comment]
> Hi, thanks for your contribution!
> Does the file in Spanish, Portuguese and Polish also have the same typo?

yes Spanish, Portuguese and Polish also have same typo just now noticed.

**Comment by jonataslaw** [comment]
> > Hi, thanks for your contribution!
> > Does the file in Spanish, Portuguese and Polish also have the same typo?
> 
> yes Spanish, Portuguese and Polish also have same typo just now noticed.

Would it be possible to include this change in that PR? Please.

**Comment by gokul1630** [comment]
> > > Hi, thanks for your contribution!
> > > Does the file in Spanish, Portuguese and Polish also have the same typo?
> > 
> > 
> > yes Spanish, Portuguese and Polish also have same typo just now noticed.
> 
> Would it be possible to include this change in that PR? Please.

yea sure

**Pull request closed without merging**
