### PR TITLE
README-fr.md

### PR DESCRIPTION
**Pull request by kamazoun**
Hi everybody. 
This is the french translation of the Readme. 
Translation for state/dependency/route management soon.
Cheers

### CODE REVIEW

**Comment by eduardoflorence** [comment]
Great work!

**Comment by kamazoun** [comment]
Thank you @eduardoflorence.

**Comment by jonataslaw** [comment]
Thanks for your contribution!

**Comment by kamazoun** [comment]
My pleasure @jonataslaw.

**Comment by jonataslaw** [comment]
Thanks again for your work. Is this version ready for merge?

**Comment by kamazoun** [comment]
Hi @jonataslaw . Yes, it's all done now. I've  just added the links for the files in french inside the spanish and chinese READMEs too.

**Comment by jonataslaw** [comment]
Ok, LGTM, I'll merge

**Pull request merged**
