### PR TITLE
Try to make get_utils null safe

### PR DESCRIPTION
**Pull request by Goddchen**
To get things going, I just started with the get_utils package. Let me know what you think.

### CODE REVIEW

**Comment by Goddchen** [comment]
Yo @jonataslaw what's going on?

**Comment by NatsuOnFire** [comment]
I think it's because there is already a branch null safety
https://github.com/jonataslaw/getx/tree/null-safety

**Comment by jonataslaw** [comment]
> To get things going, I just started with the get_utils package. Let me know what you think.

Thanks for your contribution, I was unable to merge because it was based on another old branch.  I will copy your code and give the credits in the readme, if you want to join the other branch, it will be very good.  Sorry for closing without expressing it, in fact github closed automatically because I deleted the branch you were based on

**Comment by Goddchen** [comment]
> > To get things going, I just started with the get_utils package. Let me know what you think.
> 
> Thanks for your contribution, I was unable to merge because it was based on another old branch. I will copy your code and give the credits in the readme, if you want to join the other branch, it will be very good. Sorry for closing without expressing it, in fact github closed automatically because I deleted the branch you were based on

Oh ok, cool. @jonataslaw  Is there any place we could coordinate our effords? Like Discord, Slack, a GitHub issue or something like that?

**Comment by eduardoflorence** [comment]
> > > To get things going, I just started with the get_utils package. Let me know what you think.
> > 
> > 
> > Thanks for your contribution, I was unable to merge because it was based on another old branch. I will copy your code and give the credits in the readme, if you want to join the other branch, it will be very good. Sorry for closing without expressing it, in fact github closed automatically because I deleted the branch you were based on
> 
> Oh ok, cool. @jonataslaw Is there any place we could coordinate our effords? Like Discord, Slack, a GitHub issue or something like that?
https://pub.dev/packages/get/versions/4.0.0-nullsafety.2#community-channels

**Pull request closed without merging**
