### PR TITLE
fix app closing when back button tapped

### PR DESCRIPTION
**Pull request by dipflix**

### CODE REVIEW

**Comment by uzuki-P** [comment]
is this fixing issue #2883 ?

**Comment by dipflix** [comment]
Hmm, maybe not. 
This only fixes the issue of the app closing when the back button is pressed.

In the latest version of GetX, I have found a few bugs with both simple and nested navigation.
I will let you know when I fix them.

Now I use a custom disposable widget for deleting controllers from bindings.
For example: 
```
Disposable(
      onDispose: () {
        Get.delete<IProfilePresenter>();
      },
      child: ...
```

If I understand everything correctly :)

**Comment by jonataslaw** [comment]
Thank you for your contribution!

LGTM!

**Comment by Sumit258000** [comment]
Any update when it will be live. we have release in coming week?

**Comment by jonataslaw** [comment]
Yeah, definitely

**Comment by Sumit258000** [comment]
can you push this fix to some temporary git branch?

**Comment by Sumit258000** [comment]
With `get: ^4.6.6` and `flutter:3.13.1` still problem persist using `WillPopScope.`

**Comment by jonataslaw** [comment]
WillPopScope should not be used

**Comment by Sumit258000** [comment]
https://github.com/jonataslaw/getx/issues/2874#issuecomment-1709273719 Solved by removing `android:enableOnBackInvokedCallback="true"`

**Pull request merged**
