### PR TITLE
Adds restorationScopeId to GetMaterialApp

### LINKED ISSUE #1850: GetMaterialApp doesnt support restorationScopeId as parameter
Title says all. Should be easy implmentation.

### PR DESCRIPTION
**Pull request by Mayb3Nots**
fixes  #1850

### CODE REVIEW

**Comment by Jpec57** [comment]
Hey ! When should we expect this to be merged ?

**Comment by Jpec57** [comment]
Hey ! When should we expect this to be merged ?

**Comment by fotiDim** [comment]
@Mayb3Nots do you mind solving the merge conflicts?
@jonataslaw can we please have that feature?

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots do you mind solving the merge conflicts? @jonataslaw can we please have that feature?

I would love to resolve the merge conflicts. However it seems like the conflicts are coming from @jonataslaw's commit which I don't know what he wants to keep or not so I'll leave it up to him to resolve it and merge. Thanks.

**Pull request closed without merging**
