### PR TITLE
Added Persistent bottom sheet 

### PR DESCRIPTION
**Pull request by mohak852**
#503 Added Persistent bottom sheet in getx.

### CODE REVIEW

**Comment by roipeker** [comment]
@mohak852 How do you use the Bottomsheet? 
`_GetPerModalBottomSheet ` is a private class, with no external API reference, am I missing something?

**Comment by Nipodemos** [comment]
Hello!
I come here just to ask for you to not send the pubspec.lock file.

In the end @jonataslaw will overwrite the file with his own when he pushes his commits, so there is no point in doing that
the rest of the review i'll leave for jonatas to see 😅

**Comment by mohak852** [comment]
@roipeker Actually currently I am working on the final update I have just send the pr so that you can view the __GetPerModalBottomSheet_ class. If any changes in this, please refer to me.

**Comment by mohak852** [comment]
I have a doubt that how we are calling **_Get.anycoomand_** in the dart files.

**Comment by mohak852** [comment]
Waiting for your reply.

**Comment by roipeker** [comment]
the call should be at the same [level/file](https://github.com/jonataslaw/getx/blob/master/lib/src/navigation/extension_navigation.dart) as `Get.bottomSheet`.
Regarding the name, I have no idea, if it's the same method signature for **modal** and **persistent** bottomSheets, except that persistent happens at Scaffold's level (should have the option to not block the UI underneath it)... I would just add a "persistent: true/false" in the bottomSheet call. Otherwise maybe use `rawBottomSheet()` or `persistentBottomSheet()` ... anyway, if it works, and gets approved, we have a few days to change the name, before next release.

**Comment by mohak852** [comment]
@roipeker as suggested by you I have made the persistent bottom sheet as bool and now you can check this.

**Comment by jonataslaw** [comment]
LGTM, thanks for yout contribution!

**Pull request merged**
