### PR TITLE
Docs updated for logWriterCallback option

### PR DESCRIPTION
**Pull request by stefandevo**
Added docs for the logging option

### CODE REVIEW

**Comment by stefandevo** [comment]
@Nipodemos maybe you can update the -BR version too?

**Comment by stefandevo** [comment]
@ajatsoft maybe you can update the -ES version too?

**Comment by stefandevo** [comment]
@szymon-filipiak maybe you can update the -PL version too?

**Comment by Nipodemos** [comment]
i noticed that one of the best ways to truly understand a topic is to translate it. 

only after i translated that i've noticed  that this logWriter does not respect `Get.isLogEnable`. Why?

**Comment by stefandevo** [comment]
Because then you can control it from the logging package to decide to collect the log. 
Also then there is also one location in the library to check if logging is needed (see log.dart).

**Comment by Nipodemos** [comment]
oh i understand, thanks for the reply.
@jonataslaw since the other guys will need to make a new PR to translate, i think this can be approved

now i am wondering if we should put this docs in the other languages files the english version so that someone that will read the translated docs can at least acknowledge that there is a logWriterCallback.

What do you think @stefandevo , i'm wondering this for ages

**Comment by ajatsoft** [comment]
Yes, I will try to do this night

**Comment by jonataslaw** [comment]
> oh i understand, thanks for the reply.
> @jonataslaw since the other guys will need to make a new PR to translate, i think this can be approved
> 
> now i am wondering if we should put this docs in the other languages files the english version so that someone that will read the translated docs can at least acknowledge that there is a logWriterCallback.
> 
> What do you think @stefandevo , i'm wondering this for ages

I agree with the approval of this PR, as well as the inclusion, although English in the other docs

**Comment by jonataslaw** [comment]
I'll merge, then we insert the English version in the other docs while the Spanish and Polish versions are not ready.

**Comment by ajatsoft** [comment]
I update the Spanish version with it in last pr

**Pull request merged**
