### PR TITLE
fix Leakage in GetPageRoute

### PR DESCRIPTION
**Pull request by huangxc212**
fix Leakage in GetPageRoute. #2480

### CODE REVIEW

**Comment by nenaqui** [comment]
Hola

**Comment by nenaqui** [comment]
Me ayudan no entiendo estás cosas y no se cómo vine a dar aqui

**Comment by jonataslaw** [comment]
Thank you for your contribution!

LGTM

**Comment by pstrode** [comment]
@jonataslaw any chance of seeing this in a release any time soon?

**Comment by git2321231** [comment]
@jonataslaw It took me a day to track down memory leaks in my project and finally I found this. The reason seems to be that this merge request is not being merged in the latest version 4.6.6 on pub.dev. Any plans?

**Pull request merged**
