### PR TITLE
[docs] Change "namedRoutes" for "GetPages" in docs

### PR DESCRIPTION
**Pull request by Nipodemos**
Oh gosh, i can't believe i have left this for so long

Until this day, the docs were still mentioning `namedRoutes` instead of `GetPages`, which is a change made months ago...

### CODE REVIEW

**Comment by Nipodemos** [comment]
hey @jonataslaw , i have a question:
how is the syntax for nested navigation now? because in the docs are like this:

```dart
Navigator(
  key: nestedKey(1), // crie uma key com um index
  initialRoute: '/',
  onGenerateRoute: (settings) {
    if (settings.name == '/') {
      return GetRouteBase(
        page: Scaffold(
          appBar: AppBar(
            title: Text("Principal"),
          ),
          body: Center(
            child: FlatButton(
              color: Colors.blue,
              child: Text("Ir para a segunda"),
              onPressed: () {
                Get.toNamed('/segunda', id:1); // navega pela sua navegação aninhada usando o index
              },
            )
          ),
        ),
      );
    } else if (settings.name == '/segunda') {
      return GetRouteBase(
        page: Center(
          child: Scaffold(
            appBar: AppBar(
              title: Text("Principal"),
            ),
            body: Center(
              child:  Text("Segunda")
            ),
          ),
        ),
      );
    }
  }
),
```

**Comment by jonataslaw** [comment]
GetRouteBase now is GetPageRoute 

As for the current modifications, LGTM.

**Comment by Nipodemos** [comment]
conflict fixed, GetRouteBase changed to GetPageRoute
i think this can be merged now 👍

**Comment by jonataslaw** [comment]
LGTM

**Comment by wbemanuel** [comment]
@Nipodemos I think there's still something to fix. `page` is of type `GetPageBuilder`, a function returning a widget and it should look like this:

```dart
Navigator(
  key: nestedKey(1), // crie uma key com um index
  initialRoute: '/',
  onGenerateRoute: (settings) {
    if (settings.name == '/') {
      return GetRouteBase(
        page: () => Scaffold(
          appBar: AppBar(
            title: Text("Principal"),
          ),
          body: Center(
            child: FlatButton(
              color: Colors.blue,
              child: Text("Ir para a segunda"),
              onPressed: () {
                Get.toNamed('/segunda', id:1); // navega pela sua navegação aninhada usando o index
              },
            )
          ),
        ),
      );
    } else if (settings.name == '/segunda') {
      return GetRouteBase(
        page: () => Center(
          child: Scaffold(
            appBar: AppBar(
              title: Text("Principal"),
            ),
            body: Center(
              child:  Text("Segunda")
            ),
          ),
        ),
      );
    }
  }
),
```

**Comment by Nipodemos** [comment]
you are indeed correct.
I'll try to send a PR later this day to fix this

**Pull request merged**
