### PR TITLE
feat/add changelog template

### PR DESCRIPTION
**Pull request by chimon2000**
This assumes that you are tagging releases and generating the CHANGELOG using https://github.com/git-chglog/git-chglog.

By default, commits that don't follow conventional commits syntax would be discluded. In order to include previous commits, I modified the template.

Running `git-chglog --next-tag 2.0.8` produces the following output.  

```
<a name="unreleased"></a>
## [Unreleased]


<a name="2.0.8"></a>
## [2.0.8] - 2020-04-28

### Added
- update changelog template to include non-conventional commits
- support for kac changelog format, conventional commits

### Fixed
- spelling error in config

<a name="2.0.0"></a>
## [2.0.0] - 2020-04-27


- Update README.md
- update readme
- Release Get 2.0
- Update README.md


<a name="1.20.1"></a>
## [1.20.1] - 2020-04-21


- Update README.pt-br.md
- improve Get.find
- Add files via upload
- Update issue templates
- Update issue templates
- Update issue templates
- Update issue templates
- Update issue templates
- Add files via upload
- New release of Get
- change version of stable branch
- Add files via upload
- added Get.config - added LogEnable/disable - added default transition - added overlayContext - added default popGesture behaviour - fix Duration transition
- Update README.md
- Update README.md
- Update README.md
- Refactor GetRoute to add back gesture


<a name="1.13.1"></a>
## [1.13.1] - 2020-03-30


- new release
- Update routes.dart
- Compatibility with dev/master branch
- Update README.md


<a name="1.11.1"></a>
## [1.11.1] - 2020-03-04


- Add files via upload
- Update README.md
- Add files via upload
- Add files via upload
- Update README.md
- Update snack_route.dart
- release new version
- Merge pull request [#11](https://github.com/jonataslaw/get/issues/11) from claudneysessa/patch-1
- static snackbar -> add backgroundColor
- Update routes.dart
- Update README.md
- Update README.md


<a name="1.7.0"></a>
## [1.7.0] - 2020-01-30


- New release
- Update README.md
- Add files via upload
- Update README.md
- Update routes.dart
- Update README.md
- Update README.md
- Update README.md
- Update README.md
- Update getroute.dart
- Update README.md
- Update README.md
- Update README.md


<a name="1.2.1"></a>
## 1.2.1 - 2019-11-15


- Add files via upload
- Delete get.dart
- Delete routes.dart
- Delete material.dart
- Add files via upload
- Initial commit


[Unreleased]: https://github.com/jonataslaw/get/compare/2.0.8...HEAD
[2.0.8]: https://github.com/jonataslaw/get/compare/2.0.0...2.0.8
[2.0.0]: https://github.com/jonataslaw/get/compare/1.20.1...2.0.0
[1.20.1]: https://github.com/jonataslaw/get/compare/1.13.1...1.20.1
[1.13.1]: https://github.com/jonataslaw/get/compare/1.11.1...1.13.1
[1.11.1]: https://github.com/jonataslaw/get/compare/1.7.0...1.11.1
[1.7.0]: https://github.com/jonataslaw/get/compare/1.2.1...1.7.0
```

Unfortunately, because some commit messages were less descriptive, they don't capture what's in the changelog now.  For an example of how I use this package, check out https://github.com/chimon2000/remote_state/blob/master/scripts/prepare_release.sh

* Update package version 
* Pipe new version into `git-chglog`
* Replace CHANGELOG with output

### CODE REVIEW

**Comment by jonataslaw** [comment]
Thank you for that!
However, I created the project on Github after uploading the plugin, so that many PR's were left out of commits (that was my mistake). Is there any way to fix this?

**Comment by chimon2000** [comment]
@jonataslaw that may be tough.  You may have to go thru each of the bad commits on the git command line and update them: 

https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message

I would normally use a tool like GitKraken to amend commits, I don't think it's robust to handle older commit messages.

**Comment by Nipodemos** [comment]
@jonataslaw i think this PR can be closed, since it's here for far too long 😅

**Comment by ghenry** [comment]
Do we now have an automated Changelog generator?

**Comment by ryan-sf** [comment]
This can be closed if the feature is no longer desired or if there are other plans.

**Comment by chimon2000** [comment]
This can be closed if the feature is no longer desired or if there are other plans.

**Comment by jonataslaw** [comment]
The previous problem was that the project was only opened opensource after some time, and at the time of this PR, there were almost no github commits.
After that issue we already have almost 500 commits, and the version jumped from 1 to 3.
I think that now it would not be a problem to have a tool that automates changeLog, only a few changeLogs from the initial versions would be lost, at the time that this library was not even a framework, but only a package to assist in the routes.
I think that with some effort this can be implemented today, especially since the releases are being published frequently. But I leave it up to you to decide if we should move in that direction.

**Comment by Nipodemos** [comment]
@chimon2000 this would be very nice 😄

**Pull request closed without merging**
