### PR TITLE
Urdu (Pakistan) Version

### PR DESCRIPTION
**Pull request by UsamaSarwar**
Hi, my name is Usama Sarwar and I'm a Software Engineer from Pakistan. I am contributing to GetX because it's the most popular thing with Flutter. It made the life of Flutter Developers really easy. I added Urdu Documentation so that developers in my country (Pakistan) may understand and use it. It would definitely make development easier. 
Sharing is Caring 💙

### CODE REVIEW

**Comment by jonataslaw** [comment]
It is a pleasure for me to have the Urdu translation in the readme, at the beginning of the year we already did a job to facilitate RTL, and I hope to contribute more in the future with the middle east community.
Thank you for this great contribution.

**Comment by jonataslaw** [comment]
I believe that it is only necessary to include in the other readme files the reference to Urdu, in case the developers open the readme of another version, know that there is Urdu in them.
Could you change the other readme files to add the reference to Urdu?

After that, it's ready for me to merge.

**Comment by UsamaSarwar** [comment]
> I believe that it is only necessary to include in the other readme files the reference to Urdu, in case the developers open the readme of another version, know that there is Urdu in them.
> Could you change the other readme files to add the reference to Urdu?
> 
> After that, it's ready for me to merge.

Ya Sure! 💙

**Comment by UsamaSarwar** [comment]
> I believe that it is only necessary to include in the other readme files the reference to Urdu, in case the developers open the readme of another version, know that there is Urdu in them.
> Could you change the other readme files to add the reference to Urdu?
> 
> After that, it's ready for me to merge.

Done 💙

**Comment by jonataslaw** [comment]
Thanks!
LGTM

**Pull request merged**
